// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZYH6Mu_Li1kFP1CpVDnTSnMpYX5nzAcI',
    appId: '1:462754702925:web:825195db3fdf7b07f25e04',
    messagingSenderId: '462754702925',
    projectId: 'uas-kelompok-1-cf6d1',
    authDomain: 'uas-kelompok-1-cf6d1.firebaseapp.com',
    storageBucket: 'uas-kelompok-1-cf6d1.firebasestorage.app',
    measurementId: 'G-E6S6EBG8M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlsT30jyX3akmdB2sqwutggmf_fmFJ02k',
    appId: '1:462754702925:android:5f312563dfc87b2df25e04',
    messagingSenderId: '462754702925',
    projectId: 'uas-kelompok-1-cf6d1',
    storageBucket: 'uas-kelompok-1-cf6d1.firebasestorage.app',
  );
}
